enum KeyCodes {
    Any = 'Any',
    All = 'All',

    A = "KeyA",
    B = "KeyB",
    C = "KeyC",
    D = "KeyD",
    E = "KeyE",
    F = "KeyF",
    G = "KeyG",
    H = "KeyH",
    I = "KeyI",
    J = "KeyJ",
    K = "KeyK",
    L = "KeyL",
    M = "KeyM",
    N = "KeyN",
    O = "KeyO",
    P = "KeyP",
    Q = "KeyQ",
    R = "KeyR",
    S = "KeyS",
    T = "KeyT",
    U = "KeyU",
    V = "KeyV",
    W = "KeyW",
    X = "KeyX",
    Y = "KeyY",
    Z = "KeyZ",

    D0 = "Digit0",
    D1 = "Digit1",
    D2 = "Digit2",
    D3 = "Digit3",
    D4 = "Digit4",
    D5 = "Digit5",
    D6 = "Digit6",
    D7 = "Digit7",
    D8 = "Digit8",
    D9 = "Digit9",

    Num0 = "Numpad0",
    Num1 = "Numpad1",
    Num2 = "Numpad2",
    Num3 = "Numpad3",
    Num4 = "Numpad4",
    Num5 = "Numpad5",
    Num6 = "Numpad6",
    Num7 = "Numpad7",
    Num8 = "Numpad8",
    Num9 = "Numpad9",

    F1 = "F1",
    F2 = "F2",
    F3 = "F3",
    F4 = "F4",
    F5 = "F5",
    F6 = "F6",
    F7 = "F7",
    F8 = "F8",
    F9 = "F9",
    F10 = "F10",
    F11 = "F11",
    F12 = "F12",

    ArrowUp = "ArrowUp",
    ArrowDown = "ArrowDown",
    ArrowLeft = "ArrowLeft",
    ArrowRight = "ArrowRight",

    Enter = "Enter",
    Space = "Space",
    Esc = "Escape",
    Tab = "Tab",
    BackSpace = "Backspace",
    Delete = "Delete",

    ShiftLeft = "ShiftLeft",
    ShiftRight = "ShiftRight",
    CtrlLeft = "ControlLeft",
    CtrlRight = "ControlRight",
    AltLeft = "AltLeft",
    AltRight = "AltRight",
    MetaLeft = "MetaLeft",
    MetaRight = "MetaRight",
    CapsLock = "CapsLock",
    NumLock = "NumLock",

    Comma = "Comma",
    Period = "Period",
    Slash = "Slash",
    BackSlash = "Backslash",
    Semicolon = "Semicolon",
    Quote = "Quote",
    BracketLeft = "BracketLeft",
    BracketRight = "BracketRight",

    Minus = "Minus",
    Equal = "Equal"
}

export const FunctionKeys = [
    KeyCodes.AltLeft,
    KeyCodes.AltRight,
    KeyCodes.ShiftLeft,
    KeyCodes.ShiftRight,
    KeyCodes.CtrlLeft,
    KeyCodes.CtrlRight,
    KeyCodes.MetaLeft,
    KeyCodes.MetaRight
] as const

export default KeyCodes